### get all tweets
GET https://api.twitter.com/2/users/1692561577/tweets?max_results=5
Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAPIlYAEAAAAAcl9F%2B2lHdhwOHIV000PTpleFgM4%3DDDgwD0NlzM7mJoZn4M7zewzagbrSe37AW3cBCBCKyW66CcvWaF

### Post a tweet
POST https://api.twitter.com/2/tweets
Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAPIlYAEAAAAAC1IA6rids9Aa0KueD6J97O5Ko9I%3D1G9tewnYJ8zhmgW8MtU4ZPuSJtkGNRWB0IKxHShsAQtbKahuwJ
Content-Type: application/json

{
  "tweet": "test",
}

 ### facebook generate access token 
 GET https://graph.facebook.com/oauth/access_token?client_id=590641228675322&client_secret=49e346b80551b1cc6618bc1aeb2f7166&grant_type=client_credentials

### Sessions create (login)
 POST http://localhost:3000/sessions
 Content-Type: application/json

 {
   "email": "test@test.com",
   "password": "password"
 }

 

### Users create (signup)
 POST http://localhost:3000/users
 Content-Type: application/json

 {
   "name": "Test name",
   "email": "test@test.com",
   "password": "password",
   "password_confirmation": "password"
 }

 ### facebook generate access token 
 GET https://graph.facebook.com/oauth/access_token?client_id=590641228675322&client_secret=49e346b80551b1cc6618bc1aeb2f7166&grant_type=client_credentials